<?php

declare(strict_types=1);

return [

    /*
    |--------------------------------------------------------------------------
    | SISP URL
    |--------------------------------------------------------------------------
    |
    | This is the URL of the SISP payment gateway.
    | This URL is used to communicate with the SISP payment system.
    |
    */
    'url' => env('SISP_URL'),

    /*
    |--------------------------------------------------------------------------
    | Generators Configuration
    |--------------------------------------------------------------------------
    |
    | This section configures the various generators used in the payment
    | processing flow. These generators create specific values required for
    | the payment request, ensuring that the session, reference, and timestamp
    | values are dynamically generated as needed.
    |
    | Each generator is associated with an action class responsible for
    | creating the respective value. You can customize or extend these
    | actions as necessary to fit your business logic.
    |
    | The generators are as follows:
    |
    | - 'merchantSession': Generates a unique session identifier for each
    |   payment request, helping to track and differentiate between sessions.
    | - 'merchantReference': Generates a unique merchant reference for each
    |   transaction, enabling easy identification of the payment in logs or
    |   backend systems.
    | - 'timeStamp': Generates a timestamp value representing the exact time
    |   the payment request was created, which is essential for tracking and
    |   ensuring the timing of transactions.
    |
    | You can add more generators or modify the existing ones to meet your
    | specific requirements.
    |
    */
    'generators' => [
        'merchantSession' => Akira\Sisp\Actions\Generators\MerchantSessionGeneratorAction::class,
        'merchantReference' => Akira\Sisp\Actions\Generators\MerchantReferenceGeneratorAction::class,
        'timeStamp' => Akira\Sisp\Actions\Generators\TimeStampGeneratorAction::class,
    ],

    /*
    |--------------------------------------------------------------------------
    | Merchant Virtual POS Terminal Identification
    |--------------------------------------------------------------------------
    |
    | This identifier is generated by SISP and provided to the merchant.
    | It uniquely identifies the merchant's virtual POS terminal.
    |
    */
    'posID' => env('SISP_POS_ID'),

    /*
    |--------------------------------------------------------------------------
    | Merchant Virtual POS Terminal Password
    |--------------------------------------------------------------------------
    |
    | This password is generated by SISP and provided to the merchant.
    | It is used for authentication during the payment process.
    |
    */
    'posAutCode' => env('SISP_POS_AUT_CODE'),

    /*
    |--------------------------------------------------------------------------
    | Currency Code for the Transaction
    |--------------------------------------------------------------------------
    |
    | This is a three-digit code as defined in ISO 4217.
    | It represents the currency of the transaction, which should always be '132'
    | for Cape Verde Escudo (CVE).
    |
    */
    'currency' => env('SISP_CURRENCY', '132'),

    /*
    |--------------------------------------------------------------------------
    | Language for Transaction Response Messages
    |--------------------------------------------------------------------------
    |
    | This is a two-letter code as defined in ISO 639-1.
    | Default is 'EN' for English. You can change it to 'PT' for Portuguese.
    |
    */
    'language_messages' => env('SISP_LANGUAGE_MESSAGES', 'EN'),

    /*
    |--------------------------------------------------------------------------
    | Fingerprint Algorithm Version
    |--------------------------------------------------------------------------
    |
    | This is the version of the fingerprint algorithm used for authentication.
    | The default is '1'.
    |
    */
    'fingerprint_version' => env('SISP_FINGERPRINT_VERSION', '1'),

    /*
    |--------------------------------------------------------------------------
    | URL for Merchant's Server Response
    |--------------------------------------------------------------------------
    |
    | This is the URL of the merchant's server where the merchant will receive
    | the response from SISP after the transaction is processed.
    |
    */
    'url_merchant_response' => env('SISP_URL_MERCHANT_RESPONSE'),

    /*
    |--------------------------------------------------------------------------
    | 3D Secure Transaction Indicator
    |--------------------------------------------------------------------------
    |
    | This option indicates whether the transaction is 3D Secure or not.
    | Default is '0' for non-3D Secure transactions.
    |
    */
    'is_3dsec' => env('SISP_IS_3D_SEC', '0'),

    /*
    |--------------------------------------------------------------------------
    | Transaction Code
    |--------------------------------------------------------------------------
    |
    | Type of transaction being initiated.
    | This could define the type of payment, such as purchase or refund.
    |
    */
    'transaction_code' => env('SISP_DEFAULT_TRANSACTION_CODE', '1'),

    /*
    |--------------------------------------------------------------------------
    | Merchant Identification
    |--------------------------------------------------------------------------
    |
    | This identifier is generated by SISP and provided to the merchant.
    | It is unique to each merchant for transaction identification.
    |
    */
    'merchantId' => env('SISP_MERCHANT_ID'),

    /*
    |--------------------------------------------------------------------------
    | Database Tables Configuration
    |--------------------------------------------------------------------------
    |
    | Configure the names of all SISP-related tables to avoid conflicts with
    | other packages or custom tables in your application.
    |
    */
    'tables' => [
        'transactions' => env('SISP_TABLE_TRANSACTIONS', 'sisp_transactions'),
        'transaction_items' => env('SISP_TABLE_TRANSACTION_ITEMS', 'sisp_transaction_items'),
        'invoices' => env('SISP_TABLE_INVOICES', 'sisp_invoices'),
    ],

    /*
    | Deprecated: Use tables.transactions instead
    */
    'table_name' => env('SISP_TABLE_TRANSACTIONS', 'sisp_transactions'),

    /*
    |--------------------------------------------------------------------------
    | Redirect URL After Payment or Cancellation
    |--------------------------------------------------------------------------
    |
    | This is the URL to which users will be redirected after a successful payment or
    | cancellation. Make sure it corresponds to your application's flow.
    |
    */
    'redirect_url' => env('SISP_REDIRECT_URL', '/'),

    /*
    |--------------------------------------------------------------------------
    | Theme for the Payment Page
    |--------------------------------------------------------------------------
    |
    | This option defines the theme of the payment page. It can be either 'dark' or 'light'.
    | Default is 'dark'.
    |
    */
    'theme' => env('SISP_THEME', 'white'),

    'sandbox' => env('SISP_SANDBOX', false),

    'use_blade' => [
        'enabled' => env('SISP_USE_BLADE', true),
        'payment_form' => 'sisp::payment-form',
        'payment_response' => 'sisp::payment-response',

    ],

    'use_inertia' => [
        'enabled' => env('SISP_USE_INERTIA', false),
        'payment_form_component' => env('SISP_INERTIA_PAYMENT_COMPONENT', 'Sisp/PaymentForm'),
        'payment_response_component' => env('SISP_INERTIA_CALLBACK_COMPONENT', 'Sisp/PaymentResponse'),
    ],

    'invoice' => [
        'number_format' => env('SISP_INVOICE_NUMBER_FORMAT', 'date-based'),
        'prefix' => env('SISP_INVOICE_NUMBER_PREFIX', 'INV'),
    ],

];
