<?php

declare(strict_types=1);

return [

    /*
    |--------------------------------------------------------------------------
    | SISP URL
    |--------------------------------------------------------------------------
    |
    | This is the URL of the SISP payment gateway.
    | This URL is used to communicate with the SISP payment system.
    |
    */
    'url' => env('SISP_URL'),

    /*
    |--------------------------------------------------------------------------
    | Generators Configuration
    |--------------------------------------------------------------------------
    |
    | This section configures the various generators used in the payment
    | processing flow. These generators create specific values required for
    | the payment request, ensuring that the session, reference, and timestamp
    | values are dynamically generated as needed.
    |
    | Each generator is associated with an action class responsible for
    | creating the respective value. You can customize or extend these
    | actions as necessary to fit your business logic.
    |
    | The generators are as follows:
    |
    | - 'merchantSession': Generates a unique session identifier for each
    |   payment request, helping to track and differentiate between sessions.
    | - 'merchantReference': Generates a unique merchant reference for each
    |   transaction, enabling easy identification of the payment in logs or
    |   backend systems.
    | - 'timeStamp': Generates a timestamp value representing the exact time
    |   the payment request was created, which is essential for tracking and
    |   ensuring the timing of transactions.
    |
    | You can add more generators or modify the existing ones to meet your
    | specific requirements.
    |
    */
    'generators' => [
        'merchantSession' => Akira\Sisp\Actions\Generators\MerchantSessionGeneratorAction::class,
        'merchantReference' => Akira\Sisp\Actions\Generators\MerchantReferenceGeneratorAction::class,
        'timeStamp' => Akira\Sisp\Actions\Generators\TimeStampGeneratorAction::class,
    ],

    /*
    |--------------------------------------------------------------------------
    | Merchant Virtual POS Terminal Identification
    |--------------------------------------------------------------------------
    |
    | This identifier is generated by SISP and provided to the merchant.
    | It uniquely identifies the merchant's virtual POS terminal.
    |
    */
    'posID' => env('SISP_POS_ID'),

    /*
    |--------------------------------------------------------------------------
    | Merchant Virtual POS Terminal Password
    |--------------------------------------------------------------------------
    |
    | This password is generated by SISP and provided to the merchant.
    | It is used for authentication during the payment process.
    |
    */
    'posAutCode' => env('SISP_POS_AUT_CODE'),

    /*
    |--------------------------------------------------------------------------
    | Currency Code for the Transaction
    |--------------------------------------------------------------------------
    |
    | This is a three-digit code as defined in ISO 4217.
    | It represents the currency of the transaction, which should always be '132'
    | for Cape Verde Escudo (CVE).
    |
    */
    'currency' => env('SISP_CURRENCY', '132'),

    /*
    |--------------------------------------------------------------------------
    | Language for Transaction Response Messages
    |--------------------------------------------------------------------------
    |
    | This is a two-letter code as defined in ISO 639-1.
    | Default is 'en' for English. You can change it to 'pt' for Portuguese.
    |
    */
    'languageMessages' => env('SISP_LANGUAGE_MESSAGES', 'en'),

    /*
    |--------------------------------------------------------------------------
    | Fingerprint Algorithm Version
    |--------------------------------------------------------------------------
    |
    | This is the version of the fingerprint algorithm used for authentication.
    | The default is '1'.
    |
    */
    'fingerPrintVersion' => env('SISP_FINGERPRINT_VERSION', '1'),

    /*
    |--------------------------------------------------------------------------
    | URL for Merchant's Server Response
    |--------------------------------------------------------------------------
    |
    | This is the URL of the merchant's server where the merchant will receive
    | the response from SISP after the transaction is processed.
    |
    */
    'urlMerchantResponse' => config('app.url').'/sisp-payment-response',

    /*
    |--------------------------------------------------------------------------
    | 3D Secure Transaction Indicator
    |--------------------------------------------------------------------------
    |
    | This option indicates whether the transaction is 3D Secure or not.
    | Default is '1' for 3D Secure transactions.
    |
    */
    'is3DSec' => env('SISP_IS_3D_SEC', '1'),

    /*
    |--------------------------------------------------------------------------
    | Transaction Code
    |--------------------------------------------------------------------------
    |
    | Type of transaction being initiated.
    | This could define the type of payment, such as purchase or refund.
    |
    */
    'transactionCode' => env('SISP_DEFAULT_TRANSACTION_CODE', '1'),

    /*
    |--------------------------------------------------------------------------
    | Merchant Identification
    |--------------------------------------------------------------------------
    |
    | This identifier is generated by SISP and provided to the merchant.
    | It is unique to each merchant for transaction identification.
    |
    */
    'merchantId' => env('SISP_MERCHANT_ID'),

    /*
    |--------------------------------------------------------------------------
    | Transaction Table Name
    |--------------------------------------------------------------------------
    |
    | The name of the table where transaction records will be stored in the database.
    |
    */
    'table_name' => 'sisp_transactions',

    /*
    |--------------------------------------------------------------------------
    | Redirect URL After Payment or Cancellation
    |--------------------------------------------------------------------------
    |
    | This is the URL to which users will be redirected after a successful payment or
    | cancellation. Make sure it corresponds to your application's flow.
    |
    */
    'redirect_url' => env('SISP_REDIRECT_URL', '/'),

    /*
    |--------------------------------------------------------------------------
    | Theme for the Payment Page
    |--------------------------------------------------------------------------
    |
    | This option defines the theme of the payment page. It can be either 'dark' or 'light'.
    | Default is 'dark'.
    |
    */
    'theme' => env('SISP_THEME', 'white'),

];
