<?php

declare(strict_types=1);

return [

    /*
    |--------------------------------------------------------------------------
    | SISP URL
    |--------------------------------------------------------------------------
    |
    | This is the URL of the SISP payment gateway.
    | This URL is used to communicate with the SISP payment system.
    |
    */
    'url' => env('SISP_URL'),

    /*
    |--------------------------------------------------------------------------
    | Generators Configuration
    |--------------------------------------------------------------------------
    |
    | This section configures the various generators used in the payment
    | processing flow. These generators create specific values required for
    | the payment request, ensuring that the session, reference, and timestamp
    | values are dynamically generated as needed.
    |
    | Each generator is associated with an action class responsible for
    | creating the respective value. You can customize or extend these
    | actions as necessary to fit your business logic.
    |
    | The generators are as follows:
    |
    | - 'merchantSession': Generates a unique session identifier for each
    |   payment request, helping to track and differentiate between sessions.
    | - 'merchantReference': Generates a unique merchant reference for each
    |   transaction, enabling easy identification of the payment in logs or
    |   backend systems.
    | - 'timeStamp': Generates a timestamp value representing the exact time
    |   the payment request was created, which is essential for tracking and
    |   ensuring the timing of transactions.
    |
    | You can add more generators or modify the existing ones to meet your
    | specific requirements.
    |
    */
    'generators' => [
        'merchantSession' => Akira\Sisp\Actions\Generators\MerchantSessionGeneratorAction::class,
        'merchantReference' => Akira\Sisp\Actions\Generators\MerchantReferenceGeneratorAction::class,
        'timeStamp' => Akira\Sisp\Actions\Generators\TimeStampGeneratorAction::class,
    ],

    /*
    |--------------------------------------------------------------------------
    | Merchant Virtual POS Terminal Identification
    |--------------------------------------------------------------------------
    |
    | This identifier is generated by SISP and provided to the merchant.
    | It uniquely identifies the merchant's virtual POS terminal.
    |
    */
    'posID' => env('SISP_POS_ID'),

    /*
    |--------------------------------------------------------------------------
    | Merchant Virtual POS Terminal Password
    |--------------------------------------------------------------------------
    |
    | This password is generated by SISP and provided to the merchant.
    | It is used for authentication during the payment process.
    |
    */
    'posAutCode' => env('SISP_POS_AUT_CODE'),

    /*
    |--------------------------------------------------------------------------
    | Currency Code for the Transaction
    |--------------------------------------------------------------------------
    |
    | This is a three-digit code as defined in ISO 4217.
    | It represents the currency of the transaction, which should always be '132'
    | for Cape Verde Escudo (CVE).
    |
    */
    'currency' => env('SISP_CURRENCY', '132'),

    /*
    |--------------------------------------------------------------------------
    | Language for Transaction Response Messages
    |--------------------------------------------------------------------------
    |
    | This is a two-letter code as defined in ISO 639-1.
    | Default is 'EN' for English. You can change it to 'PT' for Portuguese.
    |
    */
    'language_messages' => env('SISP_LANGUAGE_MESSAGES', 'EN'),

    /*
    |--------------------------------------------------------------------------
    | Fingerprint Algorithm Version
    |--------------------------------------------------------------------------
    |
    | This is the version of the fingerprint algorithm used for authentication.
    | The default is '1'.
    |
    */
    'fingerprint_version' => env('SISP_FINGERPRINT_VERSION', '1'),

    /*
    |--------------------------------------------------------------------------
    | URL for Merchant's Server Response
    |--------------------------------------------------------------------------
    |
    | This is the URL of the merchant's server where the merchant will receive
    | the response from SISP after the transaction is processed.
    |
    */
    'url_merchant_response' => env('SISP_URL_MERCHANT_RESPONSE'),

    /*
    |--------------------------------------------------------------------------
    | 3D Secure Transaction Indicator
    |--------------------------------------------------------------------------
    |
    | This option indicates whether the transaction is 3D Secure or not.
    | Default is '0' for non-3D Secure transactions.
    |
    */
    'is_3dsec' => env('SISP_IS_3D_SEC', '0'),

    /*
    |--------------------------------------------------------------------------
    | Transaction Code
    |--------------------------------------------------------------------------
    |
    | Type of transaction being initiated.
    | This could define the type of payment, such as purchase or refund.
    |
    */
    'transaction_code' => env('SISP_DEFAULT_TRANSACTION_CODE', '1'),

    /*
    |--------------------------------------------------------------------------
    | Merchant Identification
    |--------------------------------------------------------------------------
    |
    | This identifier is generated by SISP and provided to the merchant.
    | It is unique to each merchant for transaction identification.
    |
    */
    'merchantId' => env('SISP_MERCHANT_ID'),

    /*
    |--------------------------------------------------------------------------
    | Database Tables Configuration
    |--------------------------------------------------------------------------
    |
    | Configure the names of all SISP-related tables to avoid conflicts with
    | other packages or custom tables in your application.
    |
    */
    'tables' => [
        'transactions' => env('SISP_TABLE_TRANSACTIONS', 'sisp_transactions'),
        'transaction_items' => env('SISP_TABLE_TRANSACTION_ITEMS', 'sisp_transaction_items'),
        'invoices' => env('SISP_TABLE_INVOICES', 'sisp_invoices'),
        'request_metadata' => env('SISP_TABLE_REQUEST_METADATA', 'sisp_request_metadata'),
        'rate_limits' => env('SISP_TABLE_RATE_LIMITS', 'sisp_rate_limits'),
        'blacklist' => env('SISP_TABLE_BLACKLIST', 'sisp_blacklist'),
    ],

    /*
    | Deprecated: Use tables.transactions instead
    */
    'table_name' => env('SISP_TABLE_TRANSACTIONS', 'sisp_transactions'),

    /*
    |--------------------------------------------------------------------------
    | Redirect URL After Payment or Cancellation
    |--------------------------------------------------------------------------
    |
    | This is the URL to which users will be redirected after a successful payment or
    | cancellation. Make sure it corresponds to your application's flow.
    |
    */
    'redirect_url' => env('SISP_REDIRECT_URL', '/'),

    /*
    |--------------------------------------------------------------------------
    | Sandbox Mode
    |--------------------------------------------------------------------------
    |
    | When enabled, the SISP payment gateway operates in sandbox mode for testing.
    | This allows you to test payment flows without processing real transactions.
    | Set to false in production environments.
    |
    */
    'sandbox' => env('SISP_SANDBOX', false),

    /*
    |--------------------------------------------------------------------------
    | Blade Template Rendering
    |--------------------------------------------------------------------------
    |
    | Configuration for server-side rendered Blade templates.
    | Enable this if you're using traditional Blade templates for payment forms
    | and response pages. You can customize the view paths for payment form
    | and payment response components.
    |
    | - 'enabled': Toggle Blade rendering on/off
    | - 'payment_form': View path for the payment form template
    | - 'payment_response': View path for the payment response template
    |
    */
    'use_blade' => [
        'enabled' => env('SISP_USE_BLADE', true),
        'payment_form' => 'sisp::payment-form',
        'payment_response' => 'sisp::payment-response',
    ],

    /*
    |--------------------------------------------------------------------------
    | Inertia.js Rendering
    |--------------------------------------------------------------------------
    |
    | Configuration for client-side rendered Inertia.js components.
    | Enable this if you're using Inertia.js with React or Vue for payment forms
    | and response pages. Specify the component paths that Inertia should load.
    |
    | - 'enabled': Toggle Inertia rendering on/off
    | - 'payment_form_component': Inertia component path for payment form
    | - 'payment_response_component': Inertia component path for payment response
    |
    */
    'use_inertia' => [
        'enabled' => env('SISP_USE_INERTIA', false),
        'payment_form_component' => env('SISP_INERTIA_PAYMENT_COMPONENT', 'sisp/payment-form'),
        'payment_response_component' => env('SISP_INERTIA_CALLBACK_COMPONENT', 'sisp/payment-response'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Invoice Configuration
    |--------------------------------------------------------------------------
    |
    | Settings for generating and storing invoices after successful transactions.
    | Configure the invoice number format, file storage location, and company
    | details that will appear on invoices.
    |
    | - 'number_format': Format for invoice numbers (date-based, sequential, etc.)
    | - 'prefix': Prefix to add to invoice numbers (e.g., 'INV-')
    | - 'disk': Laravel filesystem disk for storing invoices
    | - 'template': Template style for invoice generation (branded, minimal, etc.)
    | - 'temporary_url_expiration_hours': Hours for S3 temporary URL expiration (default: 24)
    | - 'company_*': Company information displayed on invoices
    |
    */
    'invoice' => [
        'number_format' => env('SISP_INVOICE_NUMBER_FORMAT', 'date-based'),
        'prefix' => env('SISP_INVOICE_NUMBER_PREFIX', 'INV'),
        'disk' => env('SISP_INVOICE_DISK', 'public'),
        'template' => env('SISP_INVOICE_TEMPLATE', 'branded'),
        'temporary_url_expiration_hours' => env('SISP_INVOICE_TEMPORARY_URL_EXPIRATION_HOURS', 24),
        'company_name' => env('SISP_COMPANY_NAME', ''),
        'company_address' => env('SISP_COMPANY_ADDRESS', ''),
        'company_code' => env('SISP_COMPANY_CODE', ''),
        'company_country' => env('SISP_COMPANY_COUNTRY', ''),
        'company_phone' => env('SISP_COMPANY_PHONE', ''),
        'company_email' => env('SISP_COMPANY_EMAIL', ''),
        'company_website' => env('SISP_COMPANY_WEBSITE', ''),
    ],

    /*
    |--------------------------------------------------------------------------
    | Retry Payment Configuration
    |--------------------------------------------------------------------------
    |
    | Controls whether users can retry failed payment transactions.
    | When enabled, a "Try Again" button will be displayed on the payment
    | response page for failed transactions, allowing users to attempt payment
    | again using the same transaction details.
    |
    */
    'allow_retry' => env('SISP_ALLOW_RETRY', true),

    /*
    |--------------------------------------------------------------------------
    | Rate Limiting Configuration
    |--------------------------------------------------------------------------
    |
    | Settings to prevent abuse and protect against brute force attacks.
    | Configure rate limits per IP address, merchant, and individual user.
    | Each limit is specified as a number of requests within a time window.
    |
    | - 'enabled': Global toggle for rate limiting
    | - 'per_ip.enabled': Enable/disable IP-based rate limiting
    | - 'per_ip.limit': Maximum requests allowed per IP
    | - 'per_ip.window_seconds': Time window in seconds for IP rate limit
    | - 'per_merchant.enabled': Enable/disable merchant-based rate limiting
    | - 'per_merchant.limit': Maximum requests allowed per merchant
    | - 'per_merchant.window_seconds': Time window for merchant rate limit
    | - 'per_user.enabled': Enable/disable user-based rate limiting
    | - 'per_user.limit': Maximum requests allowed per user
    | - 'per_user.window_seconds': Time window for user rate limit
    |
    */
    'rate_limiting' => [
        'enabled' => env('SISP_RATE_LIMITING_ENABLED', true),
        'per_ip' => [
            'enabled' => env('SISP_RATE_LIMIT_PER_IP', true),
            'limit' => env('SISP_RATE_LIMIT_PER_IP_LIMIT', 100),
            'window_seconds' => env('SISP_RATE_LIMIT_PER_IP_WINDOW', 3600),
        ],
        'per_merchant' => [
            'enabled' => env('SISP_RATE_LIMIT_PER_MERCHANT', true),
            'limit' => env('SISP_RATE_LIMIT_PER_MERCHANT_LIMIT', 500),
            'window_seconds' => env('SISP_RATE_LIMIT_PER_MERCHANT_WINDOW', 3600),
        ],
        'per_user' => [
            'enabled' => env('SISP_RATE_LIMIT_PER_USER', true),
            'limit' => env('SISP_RATE_LIMIT_PER_USER_LIMIT', 50),
            'window_seconds' => env('SISP_RATE_LIMIT_PER_USER_WINDOW', 3600),
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Security Configuration
    |--------------------------------------------------------------------------
    |
    | Advanced security settings for payment transaction protection.
    | Configure fraud detection, VPN/proxy blocking, and transaction limits.
    |
    | - 'collect_metadata': Collect device and browser metadata for fraud detection
    | - 'detect_vpn': Detect and flag transactions from VPN services
    | - 'detect_proxy': Detect and flag transactions from proxy services
    | - 'calculate_risk_score': Calculate risk score for each transaction
    | - 'max_amount_per_day': Maximum transaction amount allowed per day (null = unlimited)
    | - 'max_amount_per_month': Maximum transaction amount allowed per month (null = unlimited)
    | - 'block_new_country_payments': Block payments from countries where user hasn't transacted before
    | - 'block_vpn_proxy': Block transactions from detected VPN/proxy services
    | - 'require_whitelist': Require IP addresses to be whitelisted before payment
    |
    */
    'security' => [
        'collect_metadata' => env('SISP_COLLECT_METADATA', true),
        'detect_vpn' => env('SISP_DETECT_VPN', true),
        'detect_proxy' => env('SISP_DETECT_PROXY', true),
        'calculate_risk_score' => env('SISP_CALCULATE_RISK_SCORE', true),
        'max_amount_per_day' => env('SISP_MAX_AMOUNT_PER_DAY'),
        'max_amount_per_month' => env('SISP_MAX_AMOUNT_PER_MONTH'),
        'block_new_country_payments' => env('SISP_BLOCK_NEW_COUNTRY_PAYMENTS', false),
        'block_vpn_proxy' => env('SISP_BLOCK_VPN_PROXY', true),
        'require_whitelist' => env('SISP_REQUIRE_WHITELIST', false),
    ],

    /*
    |--------------------------------------------------------------------------
    | Geolocation Configuration
    |--------------------------------------------------------------------------
    |
    | Settings for geolocation detection and IP-based location services.
    | Used for security checks and fraud prevention analysis.
    |
    | - 'provider': Geolocation service provider (maxmind, ip-api, etc.)
    | - 'maxmind_key': API key for MaxMind GeoIP2 service
    | - 'ip_api_key': API key for IP-API service
    | - 'cache_ttl_minutes': Cache duration for geolocation data in minutes
    |
    */
    'geolocation' => [
        'provider' => env('SISP_GEOLOCATION_PROVIDER', 'maxmind'),
        'maxmind_key' => env('MAXMIND_KEY'),
        'ip_api_key' => env('IP_API_KEY'),
        'cache_ttl_minutes' => env('SISP_GEOLOCATION_CACHE_TTL', 1440),
    ],

];
