<?php

namespace Akira\Sisp;

use Akira\Sisp\Commands\LaravelSispInstallCommand;
use Illuminate\View\Compilers\BladeCompiler;
use Spatie\LaravelPackageTools\Package;
use Spatie\LaravelPackageTools\PackageServiceProvider;

class SispServiceProvider extends PackageServiceProvider
{
    public function configurePackage(Package $package): void
    {

        $package
            ->name('laravel-sisp')
            ->hasConfigFile()
            ->hasViews()
            ->hasMigration('create_laravel_sisp_table')
            ->hasRoutes('web')
//            ->hasAssets()
            ->hasCommand(LaravelSispInstallCommand::class);
    }

    public function boot()
    {
        $this->registerComponents();

        return parent::boot(); // TODO: Change the autogenerated stub
    }

    private function registerComponents(): void
    {
        $this->publishes([
            __DIR__.'/../resources/css' => public_path('vendor/sisp/css'),
        ], 'sisp-assets');

        $this->callAfterResolving('blade.compiler', function (BladeCompiler $blade) {
            $blade->anonymousComponentNamespace('akira-sisp', __DIR__.'/../resources/views/components');
        });
    }
}
