name: Tests

on:
  push:
    branches: [ 1.x, 2.x ]
  pull_request:
    branches: [ 1.x, 2.x ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        php: [ 8.5 ]
        laravel: [ 13.* ]
        stability: [ prefer-lowest, prefer-stable ]
        include:
          - laravel: 13.*
            testbench: ^11.0

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: xdebug
          tools: composer:v2

      - name: Install Aspell
        timeout-minutes: 5
        run: sudo apt-get update && sudo apt-get install -y aspell aspell-en

      - name: Install dependencies
        run: |
          composer require "illuminate/contracts:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-progress --no-interaction

      - name: Run static analysis and quality gates (Pest)
        run: composer test

      - name: Run test suite (Pest)
        run: vendor/bin/pest --compact
