name: Laravel Sisp - CI Pipeline

on:
  push:
    branches:
      - '1.x'
      - 'main'
  pull_request:
    branches:
      - '1.x'
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [ 8.2, 8.3, 8.4 ]
        laravel-version: [ '11.*', '12.*' ]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      # Set up PHP with the matrix version
      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, bcmath, openssl

      # Install Composer
      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar --version

      # Clear Composer cache to prevent issues with old packages
      - name: Clear Composer cache
        run: composer clear-cache

      # Install dependencies with the Laravel version from the matrix
      - name: Install dependencies for Laravel ${{ matrix.laravel-version }}
        run: |
          composer require "laravel/framework:${{ matrix.laravel-version }}" --no-interaction --prefer-dist
          composer install --no-interaction --prefer-dist --dev

      # Run tests
      - name: Run tests with Pest
        run: |
          composer test