name: Laravel Sisp - CI Pipeline

on:
  push:
    branches:
      - '1.x'
      - 'main'
  pull_request:
    branches:
      - '1.x'
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [ 8.2, 8.3, 8.4 ]
        laravel-version: [ '11.*', '12.*' ]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, bcmath, openssl, xdebug
          coverage: xdebug

      - name: Clear Composer cache
        run: composer clear-cache

      - name: Install dependencies with Laravel ${{ matrix.laravel-version }}
        run: |
          composer update --prefer-dist --no-interaction --with="laravel/framework:${{ matrix.laravel-version }}"

      - name: Run tests with Pest
        run: composer test